package com.github.idemura.cimple.compiler.codegen.c;

import com.github.idemura.cimple.compiler.IndentWriter;
import com.github.idemura.cimple.compiler.ast.AstModule;
import com.github.idemura.cimple.compiler.codegen.CodeGenerator;

public class CCodeGenerator extends CodeGenerator {
  private final IndentWriter out;

  public CCodeGenerator(Appendable out) {
    this.out = new IndentWriter(out, 2);
  }

  @Override
  public void generateCode(AstModule module) {
    emitPrologue();
    module.accept(new CCodeGeneratorVisitor(out));
    emitEpilogue();
  }

  private void emitPrologue() {
    out.writeLine(
      """
      // Generated by Cimple compiler

      #include <stdbool.h>
      #include <stdint.h>
      #include <stddef.h>
      #include <memory.h>
      
      typedef float float32_t;
      typedef double float64_t;
      """);
  }

  private void emitEpilogue() {
    // No epilogue yet.
  }
}
