package com.github.idemura.cimple.compiler.codegen.c;

import com.github.idemura.cimple.compiler.IndentWriter;
import com.github.idemura.cimple.compiler.ast.AstModule;
import com.github.idemura.cimple.compiler.codegen.CodeGenerator;

public class CCodeGenerator extends CodeGenerator {
  private final IndentWriter out;

  public CCodeGenerator(IndentWriter out) {
    this.out = out;
  }

  @Override
  public void generateCode(AstModule module) {
    emitPrologue();
    module.accept(new CCodeGeneratorVisitor());
    emitEpilogue();
  }

  private void emitPrologue() {
    out.writeLine(
        """
      // Generated by Cimple compiler

      #include <stdbool.h>
      #include <stddef.h>
      #include <memory.h>

      """);
  }

  private void emitEpilogue() {
    // No epilogue yet.
  }
}
