package com.github.idemura.cimple.codegen.c;

import com.github.idemura.cimple.common.CimpleException;
import com.github.idemura.cimple.common.IndentWriter;
import com.github.idemura.cimple.compiler.AstAbstractNode;
import com.github.idemura.cimple.compiler.AstBlock;
import com.github.idemura.cimple.compiler.AstFunction;
import com.github.idemura.cimple.compiler.AstVisitor;
import com.github.idemura.cimple.compiler.CodeGen;
import com.github.idemura.cimple.compiler.TypeRef;

public class CodeGenC extends AstVisitor implements CodeGen {
  private final IndentWriter out;

  CodeGenC(IndentWriter out) {
    this.out = out;
  }

  @Override
  public void generateCode(AstAbstractNode root) {
    emitPrologue();
    root.accept(this);
    emitEpilogue();
  }

  private void emitPrologue() {
    out.writeLine(
        """
      // Generated by Cimple compiler

      #include <stdbool.h>
      #include <stddef.h>
      #include <memory.h>

      """);
  }

  private void emitEpilogue() {
    // Empty
  }

  @Override
  protected void visit(AstFunction node) {
    var sb = new StringBuilder();
    sb.append("%s %s".formatted(cTypeName(node.getResultType()), node.getName()));
    sb.append("(");
    boolean first = true;
    for (var p : node.getParameters()) {
      if (!first) {
        sb.append(",");
      }
      sb.append("%s %s".formatted(cTypeName(p.getTypeRef()), p.getName()));
      first = false;
    }
    sb.append(")");
    out.writeLine(sb.toString());
    node.getBlock().accept(this);
  }

  @Override
  protected void visit(AstBlock node) {
    out.writeLine("{");
    visitChildren(node);
    out.writeLine("}");
  }

  private static String cTypeName(TypeRef typeRef) {
    return switch (typeRef.getName()) {
      case "void" -> "void";
      case "int32" -> "int32_t";
      case "int64" -> "int64_t";
      case "float32" -> "float";
      case "float64" -> "double";
      case "bool" -> "bool";
      case "string" -> "char*";
      default -> throw new CimpleException("Unknown C type %s".formatted(typeRef.getName()));
    };
  }
}
