package com.github.idemura.cimple.codegen.c;

import com.github.idemura.cimple.common.CimpleException;
import com.github.idemura.cimple.common.StringOutput;
import com.github.idemura.cimple.compiler.AstBlock;
import com.github.idemura.cimple.compiler.AstFunction;
import com.github.idemura.cimple.compiler.AstNode;
import com.github.idemura.cimple.compiler.CodeGen;
import com.github.idemura.cimple.compiler.TypeRef;
import com.github.idemura.cimple.compiler.Visitor;

public class CodeGenC extends Visitor implements CodeGen {
  private final StringOutput out;

  CodeGenC(StringOutput out) {
    this.out = out;
  }

  @Override
  public void generateCode(AstNode root) {
    emitPrologue();
    root.accept(this);
    emitEpilogue();
  }

  private void emitPrologue() {
    out.write(
        """
      // Generated by Cimple compiler

      #include <stdbool.h>
      #include <stddef.h>
      #include <memory.h>

      """);
  }

  private void emitEpilogue() {
    // Empty
  }

  @Override
  protected void visit(AstFunction node) {
    out.write("%s %s".formatted(cTypeName(node.getResultType()), node.getName()));
    out.write("(");
    boolean first = true;
    for (var p : node.getParameters()) {
      if (!first) {
        out.write(", ");
      }
      out.write("%s %s".formatted(cTypeName(p.getTypeRef()), p.getName()));
      first = false;
    }
    out.write(")");
    node.getBlock().accept(this);
  }

  @Override
  protected void visit(AstBlock node) {
    out.write("{\n");
    visitChildren(node);
    out.write("}\n");
  }

  private static String cTypeName(TypeRef typeRef) {
    return switch (typeRef.getName()) {
      case "void" -> "void";
      case "int32" -> "int32_t";
      case "int64" -> "int64_t";
      case "float32" -> "float";
      case "float64" -> "double";
      case "bool" -> "bool";
      case "string" -> "char*";
      default -> throw new CimpleException("Unknown C type %s".formatted(typeRef.getName()));
    };
  }
}
