package io.lang.cimple.compiler.codegen.c;

import io.lang.cimple.compiler.IndentWriter;
import io.lang.cimple.compiler.ast.AstModule;
import io.lang.cimple.compiler.codegen.CodeGenerator;
import java.util.List;

public class CCodeGenerator extends CodeGenerator {
  private final CCodeGeneratorParams params;
  private final IndentWriter out;

  public CCodeGenerator(CCodeGeneratorParams params, Appendable out) {
    this.params = params;
    this.out = new IndentWriter(out, 2);
  }

  @Override
  public void generateCode(List<AstModule> modules) {
    if (params.outputPreamble()) {
      emitPrologue();
    }
    for (var module : modules) {
      module.accept(new CCodeGeneratorVisitor(out, params));
    }
    if (params.outputPreamble()) {
      emitEpilogue();
    }
  }

  @Override
  public void generateCode(AstModule module) {
    generateCode(List.of(module));
  }

  private void emitPrologue() {
    out.writeLine(
        """
      // Generated by Cimple compiler

      #include <stdbool.h>
      #include <stdint.h>
      #include <stddef.h>
      #include <stdlib.h>
      #include <memory.h>
      """);
  }

  private void emitEpilogue() {
    // No epilogue yet.
  }
}
